### ISSUE TITLE
cave dweller gets triggered through blocks

### ISSUE THREAD

**Issue by ScaredSkeleton23** [SiverDX/cave_dweller#10]
Is this intentional? if it is can it be turned off in some way? 

It's kind of annoying to just be walking through a cave and be jumpscared by an aggressive cave dweller because you looked the wrong way and angered a cave dweller in an entirely seperate cave system, 

and it also messes with the flee behavior sometimes, because the cave dweller thinks you can see it when you can't

**Comment by SiverDX** [comment]
If you're on 1.19.2 you can test this version if you want
https://github.com/SiverDX/cave_dweller/releases/tag/test_build-1.19.2-1.6.2_v2

It was intentional to turn it off since line of sight check Mojang has can have issues with certain entity sizes / 1-block-wide holes
I added it back now for a certain check

Might tweak some other parts in regards to the flee behaviour

**Comment by ScaredSkeleton23** [comment]
perfect, thanks, unfortunate i play on 1.20, my fault though

**Comment by SiverDX** [comment]
Should be fixed in the latest release on CurseForge
