### ISSUE TITLE
Incompatibility with the mod Enhanced AI

### ISSUE THREAD

**Issue by Supertartory** [SiverDX/cave_dweller#3]
Something me and a friend noticed when trying to curate a modpack was with the mod [Enhanced AI](https://www.curseforge.com/minecraft/mc-mods/enhanced-ai) the dweller doesn't give chase it only flees; it acts just like a passive mob

**Comment by Supertartory** [comment]
This is for 1.19.2 btw, I forgot to mention

**Comment by SiverDX** [comment]
because they remove all previously existing target goals (targeting the player) when adding their own (to all mobs)
this obviously removes all the custom logic which might have been within those goals

https://github.com/Insane96/EnhancedAI/blob/9fce3c630902d220d879d525c5e7f53a8631d027/src/main/java/insane96mcp/enhancedai/modules/base/feature/Targeting.java#L121

this will brick various entities (or at least their targeting logic)
you will have to use their blacklist config in `enhancedai-common.toml` -> `[Base.Targeting."Entity Blacklist"]`
